{!! Form::select('department', [
'adminhr'=>'Admin &amp; HR',
'age-group'=>'Age Group Tournament',
'anti-corruption'=>'Anti-Corruption',
'board-affairs'=>'Board Affairs',
'bpl-council'=>'BPL Governing Council',
'ccdm'=>'CCDM',
'cricket-operations'=>'Cricket Operations',
'disciplinary'=>'Disciplinary',
'host'=>'Facilities Management',
'finance'=>'Finance',
'development'=>'Game Development',
'grounds'=>'Grounds',
'performance'=>'High Performance',
'Logistics'=>'Logistics and Protocol',
'marketing'=>'Marketing and Commercial',
'media'=>'Media and Communications',
'Medical'=>'Medical',
'security'=>'Security',
'tender'=>'Tender and Purchase',
'tournament'=>'Tournament',
'umpires'=>'Umpires',
'venue'=>'Venue Administration',
'women'=>'Women&rsquo;s Wing'],
null, ['class'=>'form-control select2', 'style'=>'width: 100%;']) !!}